name: unit_converter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - assets/data/regular_units.json
  - assets/icons/area.png
  - assets/icons/currency.png
  - assets/icons/digital_storage.png
  - assets/icons/length.png
  - assets/icons/mass.png
  - assets/icons/power.png
  - assets/icons/time.png
  - assets/icons/volume.png

  fonts:
  - family: Raleway
    fonts:
    - asset: third_party/Raleway-Regular.ttf
